/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : bigint,
  'name' : string,
  'color' : CarColor,
  'price' : bigint,
}
export type CarColor = { 'red' : null } |
  { 'blue' : null } |
  { 'black' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export interface Inventory { 'cars' : Array<bigint> }
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'displayName' : string,
  'createdAt' : Time,
  'totalMessagesSent' : bigint,
  'racesPlayed' : bigint,
  'averageWPM' : number,
  'bestWPM' : number,
  'accuracy' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyCar' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarCatalog' : ActorMethod<[], Array<Car>>,
  'getInventory' : ActorMethod<[Principal], Inventory>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];