/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'totalMessagesSent' : IDL.Nat,
  'racesPlayed' : IDL.Nat,
  'averageWPM' : IDL.Float64,
  'bestWPM' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const CarColor = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'black' : IDL.Null,
  'white' : IDL.Null,
  'yellow' : IDL.Null,
});
export const Car = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : CarColor,
  'price' : IDL.Nat,
});
export const Inventory = IDL.Record({ 'cars' : IDL.Vec(IDL.Nat) });
export const GrantCoinsResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Record({
    'grantedAmount' : IDL.Nat,
    'finalBalance' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyCar' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarCatalog' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getInventory' : IDL.Func([IDL.Principal], [Inventory], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantCoins' : IDL.Func([IDL.Principal, IDL.Nat], [GrantCoinsResult], []),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'totalMessagesSent' : IDL.Nat,
    'racesPlayed' : IDL.Nat,
    'averageWPM' : IDL.Float64,
    'bestWPM' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const CarColor = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'black' : IDL.Null,
    'white' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : CarColor,
    'price' : IDL.Nat,
  });
  const Inventory = IDL.Record({ 'cars' : IDL.Vec(IDL.Nat) });
  const GrantCoinsResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Record({
      'grantedAmount' : IDL.Nat,
      'finalBalance' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyCar' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarCatalog' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getInventory' : IDL.Func([IDL.Principal], [Inventory], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantCoins' : IDL.Func([IDL.Principal, IDL.Nat], [GrantCoinsResult], []),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };