/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreditResult {
  'status' : bigint,
  'creditAmount' : bigint,
  'message' : string,
  'finalBalance' : bigint,
}
export interface Holiday {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'enabled' : boolean,
}
export interface ImmutableTeam {
  'id' : bigint,
  'members' : Array<Principal>,
  'balance' : bigint,
  'name' : string,
  'memberLimit' : bigint,
  'founder' : Principal,
}
export interface Inventory { 'cars' : Array<bigint> }
export interface LeaderboardEntry {
  'wpm' : number,
  'user' : Principal,
  'combinedScore' : number,
  'accuracy' : number,
}
export type LeaderboardType = { 'wpmLeaderboard' : null } |
  { 'accuracyLeaderboard' : null } |
  { 'combinedLeaderboard' : null };
export interface RacePerformance {
  'wpm' : number,
  'raceTextId' : bigint,
  'raceTime' : bigint,
  'timestamp' : Time,
  'accuracy' : number,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'displayName' : string,
  'createdAt' : Time,
  'totalMessagesSent' : bigint,
  'racesPlayed' : bigint,
  'averageWPM' : number,
  'bestWPM' : number,
  'accuracy' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHoliday' : ActorMethod<[string, string], undefined>,
  'adminGrantTrpCoins' : ActorMethod<[bigint, Principal], CreditResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeRace' : ActorMethod<[], CreditResult>,
  'createTeam' : ActorMethod<[string], undefined>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHolidays' : ActorMethod<[], Array<Holiday>>,
  'getInventory' : ActorMethod<[Principal], Inventory>,
  'getLeaderboard' : ActorMethod<
    [LeaderboardType, [] | [bigint]],
    Array<LeaderboardEntry>
  >,
  'getRacePerformances' : ActorMethod<[Principal], Array<RacePerformance>>,
  'getTeamById' : ActorMethod<[bigint], [] | [ImmutableTeam]>,
  'getTeams' : ActorMethod<[], Array<ImmutableTeam>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'removeHoliday' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRacePerformance' : ActorMethod<[RacePerformance], undefined>,
  'updateBestPerformance' : ActorMethod<[RacePerformance], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];