/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : bigint,
  'name' : string,
  'color' : CarColor,
  'price' : bigint,
}
export type CarColor = { 'red' : null } |
  { 'blue' : null } |
  { 'black' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export type GrantCoinsResult = { 'error' : string } |
  { 'success' : { 'grantedAmount' : bigint, 'finalBalance' : bigint } };
export interface Inventory { 'cars' : Array<bigint> }
export type Season = { 'winter' : null } |
  { 'autumn' : null } |
  { 'summer' : null } |
  { 'spring' : null };
export type Time = bigint;
export type UpdateAssistantAction = { 'grantCoins' : null } |
  { 'unbanUser' : { 'adminActor' : Principal, 'targetUser' : Principal } } |
  { 'banUser' : { 'userId' : Principal, 'adminActor' : Principal } } |
  { 'changeSeason' : { 'desiredSeason' : Season, 'adminActor' : Principal } } |
  {
    'setUserBalance' : {
      'adminActor' : Principal,
      'newBalance' : bigint,
      'targetUser' : Principal,
    }
  };
export type UpdateAssistantResult = { 'error' : { 'error' : string } } |
  { 'success' : string };
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'displayName' : string,
  'createdAt' : Time,
  'banned' : boolean,
  'totalMessagesSent' : bigint,
  'racesPlayed' : bigint,
  'averageWPM' : number,
  'bestWPM' : number,
  'accuracy' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'buyCar' : ActorMethod<[bigint], undefined>,
  'executeAssistantInstruction' : ActorMethod<
    [UpdateAssistantAction],
    [] | [UpdateAssistantResult]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarCatalog' : ActorMethod<[], Array<Car>>,
  'getInventory' : ActorMethod<[Principal], Inventory>,
  'getSeason' : ActorMethod<[], Season>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantCoins' : ActorMethod<[Principal, bigint], GrantCoinsResult>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBalance' : ActorMethod<[Principal, bigint], undefined>,
  'setSeason' : ActorMethod<[Season], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];