/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreditResult = IDL.Record({
  'status' : IDL.Nat,
  'creditAmount' : IDL.Nat,
  'message' : IDL.Text,
  'finalBalance' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'totalMessagesSent' : IDL.Nat,
  'racesPlayed' : IDL.Nat,
  'averageWPM' : IDL.Float64,
  'bestWPM' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const Holiday = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const Inventory = IDL.Record({ 'cars' : IDL.Vec(IDL.Nat) });
export const LeaderboardType = IDL.Variant({
  'wpmLeaderboard' : IDL.Null,
  'accuracyLeaderboard' : IDL.Null,
  'combinedLeaderboard' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'wpm' : IDL.Float64,
  'user' : IDL.Principal,
  'combinedScore' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const RacePerformance = IDL.Record({
  'wpm' : IDL.Float64,
  'raceTextId' : IDL.Nat,
  'raceTime' : IDL.Nat,
  'timestamp' : Time,
  'accuracy' : IDL.Float64,
});
export const ImmutableTeam = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(IDL.Principal),
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'memberLimit' : IDL.Nat,
  'founder' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminGrantTrpCoins' : IDL.Func([IDL.Nat, IDL.Principal], [CreditResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeRace' : IDL.Func([], [CreditResult], []),
  'createTeam' : IDL.Func([IDL.Text], [], []),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'getInventory' : IDL.Func([IDL.Principal], [Inventory], ['query']),
  'getLeaderboard' : IDL.Func(
      [LeaderboardType, IDL.Opt(IDL.Nat)],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getRacePerformances' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RacePerformance)],
      ['query'],
    ),
  'getTeamById' : IDL.Func([IDL.Nat], [IDL.Opt(ImmutableTeam)], []),
  'getTeams' : IDL.Func([], [IDL.Vec(ImmutableTeam)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeHoliday' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRacePerformance' : IDL.Func([RacePerformance], [], []),
  'updateBestPerformance' : IDL.Func([RacePerformance], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreditResult = IDL.Record({
    'status' : IDL.Nat,
    'creditAmount' : IDL.Nat,
    'message' : IDL.Text,
    'finalBalance' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'totalMessagesSent' : IDL.Nat,
    'racesPlayed' : IDL.Nat,
    'averageWPM' : IDL.Float64,
    'bestWPM' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const Holiday = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const Inventory = IDL.Record({ 'cars' : IDL.Vec(IDL.Nat) });
  const LeaderboardType = IDL.Variant({
    'wpmLeaderboard' : IDL.Null,
    'accuracyLeaderboard' : IDL.Null,
    'combinedLeaderboard' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'wpm' : IDL.Float64,
    'user' : IDL.Principal,
    'combinedScore' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const RacePerformance = IDL.Record({
    'wpm' : IDL.Float64,
    'raceTextId' : IDL.Nat,
    'raceTime' : IDL.Nat,
    'timestamp' : Time,
    'accuracy' : IDL.Float64,
  });
  const ImmutableTeam = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(IDL.Principal),
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'memberLimit' : IDL.Nat,
    'founder' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminGrantTrpCoins' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [CreditResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeRace' : IDL.Func([], [CreditResult], []),
    'createTeam' : IDL.Func([IDL.Text], [], []),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'getInventory' : IDL.Func([IDL.Principal], [Inventory], ['query']),
    'getLeaderboard' : IDL.Func(
        [LeaderboardType, IDL.Opt(IDL.Nat)],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getRacePerformances' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RacePerformance)],
        ['query'],
      ),
    'getTeamById' : IDL.Func([IDL.Nat], [IDL.Opt(ImmutableTeam)], []),
    'getTeams' : IDL.Func([], [IDL.Vec(ImmutableTeam)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeHoliday' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRacePerformance' : IDL.Func([RacePerformance], [], []),
    'updateBestPerformance' : IDL.Func([RacePerformance], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };