/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Car {
    id: bigint;
    name: string;
    color: CarColor;
    price: bigint;
}
export type Time = bigint;
export interface Inventory {
    cars: Array<bigint>;
}
export type GrantCoinsResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: {
        grantedAmount: bigint;
        finalBalance: bigint;
    };
};
export type UpdateAssistantResult = {
    __kind__: "error";
    error: {
        error: string;
    };
} | {
    __kind__: "success";
    success: string;
};
export interface UserProfile {
    username: string;
    balance: bigint;
    displayName: string;
    createdAt: Time;
    banned: boolean;
    totalMessagesSent: bigint;
    racesPlayed: bigint;
    averageWPM: number;
    bestWPM: number;
    accuracy: number;
}
export type UpdateAssistantAction = {
    __kind__: "grantCoins";
    grantCoins: null;
} | {
    __kind__: "unbanUser";
    unbanUser: {
        adminActor: Principal;
        targetUser: Principal;
    };
} | {
    __kind__: "banUser";
    banUser: {
        userId: Principal;
        adminActor: Principal;
    };
} | {
    __kind__: "changeSeason";
    changeSeason: {
        desiredSeason: Season;
        adminActor: Principal;
    };
} | {
    __kind__: "setUserBalance";
    setUserBalance: {
        adminActor: Principal;
        newBalance: bigint;
        targetUser: Principal;
    };
};
export enum CarColor {
    red = "red",
    blue = "blue",
    black = "black",
    white = "white",
    yellow = "yellow"
}
export enum Season {
    winter = "winter",
    autumn = "autumn",
    summer = "summer",
    spring = "spring"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal): Promise<void>;
    buyCar(carId: bigint): Promise<void>;
    executeAssistantInstruction(action: UpdateAssistantAction): Promise<UpdateAssistantResult | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCarCatalog(): Promise<Array<Car>>;
    getInventory(user: Principal): Promise<Inventory>;
    getSeason(): Promise<Season>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantCoins(targetUser: Principal, amount: bigint): Promise<GrantCoinsResult>;
    initializeSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBalance(targetUser: Principal, newBalance: bigint): Promise<void>;
    setSeason(season: Season): Promise<void>;
    unbanUser(user: Principal): Promise<void>;
}
import type { Car as _Car, CarColor as _CarColor, GrantCoinsResult as _GrantCoinsResult, Season as _Season, UpdateAssistantAction as _UpdateAssistantAction, UpdateAssistantResult as _UpdateAssistantResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async buyCar(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buyCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyCar(arg0);
            return result;
        }
    }
    async executeAssistantInstruction(arg0: UpdateAssistantAction): Promise<UpdateAssistantResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.executeAssistantInstruction(to_candid_UpdateAssistantAction_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.executeAssistantInstruction(to_candid_UpdateAssistantAction_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarCatalog(): Promise<Array<Car>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarCatalog();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarCatalog();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(arg0: Principal): Promise<Inventory> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory(arg0);
            return result;
        }
    }
    async getSeason(): Promise<Season> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeason();
                return from_candid_Season_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeason();
            return from_candid_Season_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantCoins(arg0: Principal, arg1: bigint): Promise<GrantCoinsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.grantCoins(arg0, arg1);
                return from_candid_GrantCoinsResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantCoins(arg0, arg1);
            return from_candid_GrantCoinsResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBalance(arg0, arg1);
            return result;
        }
    }
    async setSeason(arg0: Season): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSeason(to_candid_Season_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSeason(to_candid_Season_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
}
function from_candid_CarColor_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarColor): CarColor {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Car_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Car): Car {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_GrantCoinsResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrantCoinsResult): GrantCoinsResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Season_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Season): Season {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateAssistantResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateAssistantResult): UpdateAssistantResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpdateAssistantResult]): UpdateAssistantResult | null {
    return value.length === 0 ? null : from_candid_UpdateAssistantResult_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    color: _CarColor;
    price: bigint;
}): {
    id: bigint;
    name: string;
    color: CarColor;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        color: from_candid_CarColor_n17(_uploadFile, _downloadFile, value.color),
        price: value.price
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: {
        error: string;
    };
} | {
    success: string;
}): {
    __kind__: "error";
    error: {
        error: string;
    };
} | {
    __kind__: "success";
    success: string;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    black: null;
} | {
    white: null;
} | {
    yellow: null;
}): CarColor {
    return "red" in value ? CarColor.red : "blue" in value ? CarColor.blue : "black" in value ? CarColor.black : "white" in value ? CarColor.white : "yellow" in value ? CarColor.yellow : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winter: null;
} | {
    autumn: null;
} | {
    summer: null;
} | {
    spring: null;
}): Season {
    return "winter" in value ? Season.winter : "autumn" in value ? Season.autumn : "summer" in value ? Season.summer : "spring" in value ? Season.spring : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: {
        grantedAmount: bigint;
        finalBalance: bigint;
    };
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: {
        grantedAmount: bigint;
        finalBalance: bigint;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Car>): Array<Car> {
    return value.map((x)=>from_candid_Car_n15(_uploadFile, _downloadFile, x));
}
function to_candid_Season_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Season): _Season {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateAssistantAction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateAssistantAction): _UpdateAssistantAction {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    desiredSeason: Season;
    adminActor: Principal;
}): {
    desiredSeason: _Season;
    adminActor: Principal;
} {
    return {
        desiredSeason: to_candid_Season_n6(_uploadFile, _downloadFile, value.desiredSeason),
        adminActor: value.adminActor
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "grantCoins";
    grantCoins: null;
} | {
    __kind__: "unbanUser";
    unbanUser: {
        adminActor: Principal;
        targetUser: Principal;
    };
} | {
    __kind__: "banUser";
    banUser: {
        userId: Principal;
        adminActor: Principal;
    };
} | {
    __kind__: "changeSeason";
    changeSeason: {
        desiredSeason: Season;
        adminActor: Principal;
    };
} | {
    __kind__: "setUserBalance";
    setUserBalance: {
        adminActor: Principal;
        newBalance: bigint;
        targetUser: Principal;
    };
}): {
    grantCoins: null;
} | {
    unbanUser: {
        adminActor: Principal;
        targetUser: Principal;
    };
} | {
    banUser: {
        userId: Principal;
        adminActor: Principal;
    };
} | {
    changeSeason: {
        desiredSeason: _Season;
        adminActor: Principal;
    };
} | {
    setUserBalance: {
        adminActor: Principal;
        newBalance: bigint;
        targetUser: Principal;
    };
} {
    return value.__kind__ === "grantCoins" ? {
        grantCoins: value.grantCoins
    } : value.__kind__ === "unbanUser" ? {
        unbanUser: value.unbanUser
    } : value.__kind__ === "banUser" ? {
        banUser: value.banUser
    } : value.__kind__ === "changeSeason" ? {
        changeSeason: to_candid_record_n5(_uploadFile, _downloadFile, value.changeSeason)
    } : value.__kind__ === "setUserBalance" ? {
        setUserBalance: value.setUserBalance
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Season): {
    winter: null;
} | {
    autumn: null;
} | {
    summer: null;
} | {
    spring: null;
} {
    return value == Season.winter ? {
        winter: null
    } : value == Season.autumn ? {
        autumn: null
    } : value == Season.summer ? {
        summer: null
    } : value == Season.spring ? {
        spring: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
